<a href="https://colab.research.google.com/github/1901010019/1901010019.github.io/blob/master/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [19]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values # will take all the rows and all the columns excluding last one.
y=  dataset.iloc[:, -1].values # will take all the rows and only the last column.

In [20]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [22]:
from sklearn.impute import SimpleImputer #importing module from the class
imputer = SimpleImputer(missing_values = np.nan, strategy='mean') # here imputer is our object.
imputer.fit(x[:, 1:3]) #specifying the rows and columns to consider, and here fit method would only consider the numerical values.
x[:, 1:3] = imputer.transform(x[:, 1:3]) #replacing old rows and columns with the updated ones.

In [15]:
print(x)

NameError: ignored

## Encoding categorical data

### Encoding the Independent Variable

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np
# data = pd.read_csv('Data.csv') 
# pd.get_dummies(data) -> this is another method for encoding.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [29]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [30]:
from sklearn.model_selection import train_test_split
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.2, random_state=1)

In [31]:
print(x_train)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [32]:
print(x_test)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [33]:
print(y_train)

[0 1]


In [34]:
print(y_test)

[0 1 0 0 1 1 0 1]


## Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[: , 3:]= sc.fit_transform(x_train[: , 3:])
x_test[: , 3:]= sc.transform(x_test[: , 3:])

In [36]:
print(x_train)

[[1.0 0.0 1.0 0.0 -1.0 -1.0]
 [0.0 1.0 0.0 0.0 1.0 1.0]]


In [37]:
print(x_test)

[[1.0 0.0 0.0 1.0 1.5079365079365081 -1.3076923076923077]
 [1.0 0.0 1.0 0.0 1.8571428571428572 0.5042735042735048]
 [0.0 1.0 0.0 0.0 3.0 1.7692307692307692]
 [1.0 0.0 0.0 1.0 1.2857142857142858 0.07692307692307693]
 [1.0 0.0 0.0 1.0 -1.8571428571428572 -1.9230769230769231]
 [0.0 1.0 0.0 0.0 4.142857142857143 2.8461538461538463]
 [1.0 0.0 1.0 0.0 4.714285714285714 3.4615384615384617]
 [0.0 1.0 0.0 0.0 0.42857142857142855 -0.38461538461538464]]
