<a href="https://colab.research.google.com/github/1901010019/1901010019.github.io/blob/master/indian_liver_patient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [80]:
dataset = pd.read_csv('indian_liver_patient.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [81]:

from sklearn.impute import SimpleImputer #importing module from the class
imputer = SimpleImputer(missing_values = np.nan, strategy='mean') # here imputer is our object.
imputer.fit(x[:, 2:10]) #specifying the rows and columns to consider, and here fit method would only consider the numerical values.
x[:, 2:10]= imputer.transform(x[:, 2:10]) #replacing old rows and columns with the updated ones.

In [82]:
print(x)

[[65 'Female' 0.7 ... 6.8 3.3 0.9]
 [62 'Male' 10.9 ... 7.5 3.2 0.74]
 [62 'Male' 7.3 ... 7.0 3.3 0.89]
 ...
 [52 'Male' 0.8 ... 6.4 3.2 1.0]
 [31 'Male' 1.3 ... 6.8 3.4 1.0]
 [38 'Male' 1.0 ... 7.3 4.4 1.5]]


In [83]:
print(y)

[1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 2 1 2 1 1 1 1 1 1 2 1 1 1 2 2 1 1 2 2 2 1 2
 1 1 1 1 2 2 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1
 1 2 1 1 2 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 2 1 2 2 2 2 2 2
 1 2 1 2 2 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1
 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1
 2 1 1 1 2 1 1 1 2 2 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 1 1 2 1 1 2 2 1 2 1 1 1
 1 2 1 1 1 1 2 1 2 1 1 1 1 1 2 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 2
 1 1 1 1 1 2 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 2 1 2 1 1 1 2 1 1 1 2 1 2 1 1
 1 2 1 2 2 1 1 2 1 2 1 1 1 1 1 1 2 2 1 2 2 1 1 2 1 1 1 2 1 2 2 2 2 2 1 1 1
 2 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 2 1 1 1 1 1 2 1 1 1 2 1 2 2 2 2 2 2 2 1 1
 1 2 1 2 2 1 1 2 1 2 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 2 1 1 2
 1 1 1 1 2 1 2 2 1 1 2 1 1 1 2 1 2 1 1 2 1 2 1 1 2 1 2 2 2 1 1 1 1 1 1 1 1
 2 2 1 1 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 2 2 2 2 2 1 1 1 1 2
 1 1 2 1 1 1 1 2 2 1 2 1 

In [84]:
 from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

columnTransformer = ColumnTransformer([('encoder', 
										OneHotEncoder(), 
										[1])], 
									remainder='passthrough') 

x = np.array(columnTransformer.fit_transform(x), dtype = np.float) 


In [85]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

In [86]:
print(x_test)

[[ 0.    1.   55.   ...  6.1   2.7   0.7 ]
 [ 0.    1.   60.   ...  7.4   3.    0.6 ]
 [ 0.    1.   38.   ...  7.5   4.2   1.2 ]
 ...
 [ 0.    1.   35.   ...  6.5   3.2   0.9 ]
 [ 0.    1.   27.   ...  6.8   3.9   1.85]
 [ 1.    0.   65.   ...  7.2   3.5   0.9 ]]


In [87]:
print(x_train)

[[ 0.   1.  55.  ...  6.2  2.9  0.8]
 [ 0.   1.  26.  ...  7.1  3.7  1. ]
 [ 1.   0.  66.  ...  6.4  3.2  1. ]
 ...
 [ 1.   0.  69.  ...  8.4  4.9  1.4]
 [ 0.   1.  60.  ...  6.6  3.5  1.1]
 [ 0.   1.  26.  ...  7.5  2.6  0.5]]


In [88]:
print(y_test)

[1 1 2 1 1 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 2 2 1 1 2 1 1 2 2 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 2 2 2 1 1 1 1 2 1 1 1 2 2 2 1 1 1 2
 2 2 2 2 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 2 1 1 2 2 1 1 1 2 1 1 1 1 2 2 2 2
 1 1 1 2 2 2]


In [89]:
print(y_train)

[2 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 2 1 2 2 1 1 1 1 1
 1 1 1 1 1 2 2 1 1 2 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 2 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 2 2 1 1 2 1 1 2 1 2 1 1 1 1
 2 1 1 2 1 1 1 1 1 2 2 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 2
 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2
 1 2 1 1 1 1 1 2 2 1 1 2 2 2 1 2 2 2 1 2 1 1 1 1 1 1 1 2 2 1 1 2 1 1 1 1 1
 1 1 1 1 2 1 2 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 2 2 2 1 1 1
 1 1 1 2 1 1 2 1 2 1 2 1 1 2 1 2 1 1 2 1 1 1 2 1 2 2 2 2 1 2 1 1 1 1 1 1 1
 1 2 1 2 1 2 2 1 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 2 1 2 1 1 1 1 2 1 2 1 1
 1 2 1 1 2 1 1 1 2 1 1 1 1 2 1 1 1 2 1 2 1 1 2 1 1 2 2 1 1 2 1 1 1 2 1 2 2
 1 2 1 2 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 1 1 1 2
 2 1 1 1 2 1 1 2 1 1 1 2 1 1 2 2 1 1 1 2 1 1 1 2 1 1 1 2 1 1 2 1 1 1 1 2 1
 2 1 1 1 1 2 2 1 1 1 1 2 1 1 1 2 1 1 1 2 1 1]


In [90]:
from sklearn.naive_bayes import GaussianNB
classifier =  GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [91]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [1 1]
 [2 1]
 [1 1]
 [2 1]
 [2 1]
 [2 1]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 2]
 [2 2]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [2 1]
 [2 1]
 [2 2]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 1]
 [2 1]
 [2 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 1]
 [2 2]
 [2 1]
 [2 1]
 [2 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 1]
 [2 1]
 [2 2]
 [2 2]
 [1 1]
 [2 1]
 [2 1]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 1]
 [2 1]
 [2 1]
 [2 2]
 [2 2]
 [2 2]]


In [92]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[32 46]
 [ 0 39]]
0.6068376068376068
