<a href="https://colab.research.google.com/github/1901010019/1901010019.github.io/blob/master/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import tensorflow as tf
import numpy as np
import pandas as pd

#performing basic operations

In [113]:
tensor = tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [114]:
tensor+10 # we can perform basic operations

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [115]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [116]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [117]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [118]:
# we can use tensorflow built in functions too
tf.multiply(tensor,10) # advantage of tensorflow function is that is speeds up your process.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

in machine learning, matrix multiplication is one of the most common tensor operations.

In [119]:
tensor2 = tf.constant([[4,5],
                       [6,7]])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

In [120]:
tf.matmul(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[82, 99],
       [36, 43]], dtype=int32)>

In [121]:
# matrix multiplication is also referred to as dot product
b = tf.constant([1.7,7.4])
b.dtype

tf.float32

In [122]:
c = tf.constant([1,7])
c.dtype

tf.int32

In [123]:
c = tf.cast(c, dtype=tf.int16)
c  # we converted an integer from 32 bit to 16 bit
# so cast function is very important function in converting the data type

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

In [124]:
tnsor = tf.constant([[-2,-4]])
tnsor

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[-2, -4]], dtype=int32)>

In [125]:
tf.abs(tnsor)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 4]], dtype=int32)>

In [126]:
tnsr = tf.constant(np.random.randint(0,100, size=50))
tnsr

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([14, 65, 58, 63, 39, 63, 88, 21, 98, 26, 28, 17, 42, 58, 15, 38, 37,
       37, 72, 90, 20, 33,  2, 92, 50, 20, 27,  7, 49, 72, 10, 67, 98, 53,
       58,  7,  4, 98, 21, 44, 47, 42, 23, 28, 43, 33, 30,  4, 36, 27])>

In [127]:
tnsr.shape, tnsr.ndim, tf.size(tnsr) # checkig the shape, size and dimension of the tensor respectively

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [128]:
tf.reduce_min(tnsr) # finding the minimum of the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [129]:
np.min(tnsr) # with the help of numpy function we tried checking the minimum element in the tensor

2

In [130]:
tf.reduce_max(tnsr)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [131]:
tf.reduce_sum(tnsr) # so here we are trying to get the sum of the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=2114>

In [132]:
import tensorflow_probability as tfp
tfp.stats.variance(tnsr) # calculated the variance

<tf.Tensor: shape=(), dtype=int64, numpy=700>

In [133]:
# calculating the standard deviation
tf.math.reduce_std(tf.cast(tnsr, dtype=tf.float32)) # we needed to change the data type of the tensor

<tf.Tensor: shape=(), dtype=float32, numpy=26.464346>

## find the positional maximum and minimum

In [134]:
# creating a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [135]:
# find the postional maximum
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [136]:
tensor[tf.argmax(tensor)] # we got the largest value from the tensor

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [137]:
# second way to find out the maximum value from the tensor
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [138]:
# checking for equality 
assert tensor[tf.argmax(tensor)] == tf.reduce_max(tensor) 
# no error means we are getting the same value

In [139]:
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [140]:
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [141]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [142]:
assert tf.reduce_min(tensor)  == tensor[tf.argmin(tensor)] # so yeah, this is also same. no difference

# squezing a tensor

In [143]:
# squeezing removes all single dimensions
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50) )
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [144]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [145]:
G_squezeed = tf.squeeze(tensor)
G_squezeed, G_squezeed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

# one hot encoding

In [146]:
# we will one hot encode any tensor with the help of tensorflow library
some_list = [1,2,3,4]
tf.one_hot(some_list, depth=4) # yay! this was easy

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

some operations over tensor

In [147]:
tf.square(tensor)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, 2.1574403e-01,
           1.1330233e-03, 4.6877623e-01, 5.4777384e-01, 7.6115942e-01,
           5.1223613e-02, 4.9816839e-02, 9.6340768e-02, 5.2176905e-01,
           1.7738823e-02, 3.0037400e-01, 3.3017528e-01, 8.0943036e-01,
           8.9561006e-05, 2.7168143e-01, 4.0264672e-01, 3.9731771e-02,
           5.3205711e-01, 2.9793534e-01, 1.1570342e-02, 4.5793110e-01,
           4.3596479e-01, 1.1353558e-01, 3.6170322e-01, 4.4363216e-02,
           7.2716069e-01, 1.9414751e-01, 8.9970458e-01, 5.6418572e-02,
           6.5900785e-01, 2.7703318e-01, 2.4434039e-01, 4.6711516e-02,
           7.1524179e-01, 7.6018190e-01, 9.5102049e-02, 4.7169948e-01,
           5.6472950e-02, 6.1109054e-01, 9.3535668e-01, 4.7199135e-03,
           6.3798469e-01, 4.3597910e-01, 3.4474665e-01, 2.7098738e-02,
           5.4479504e-01, 1.0274617e-01]]]]], dtype=float32)>

In [148]:
tf.sqrt(tensor)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.8152067 , 0.6640834 , 0.59403914, 0.6815296 , 0.18346773,
           0.8274493 , 0.86030066, 0.93404734, 0.47573766, 0.47243717,
           0.5571248 , 0.8499034 , 0.36494818, 0.74031335, 0.7580296 ,
           0.9485165 , 0.09728139, 0.72196305, 0.796583  , 0.44646195,
           0.8540623 , 0.7388061 , 0.32797182, 0.8226214 , 0.8125738 ,
           0.5804743 , 0.7755112 , 0.45893982, 0.92343765, 0.66379344,
           0.97392386, 0.48736632, 0.90099555, 0.7254925 , 0.7030704 ,
           0.4648962 , 0.9196301 , 0.93374735, 0.55532527, 0.82873625,
           0.4874838 , 0.88415086, 0.98343194, 0.26210994, 0.8937222 ,
           0.8125805 , 0.76625794, 0.40573013, 0.85912883, 0.5661629 ]]]]],
      dtype=float32)>

In [149]:
tf.math.log(tensor) # this function required to write 'math' with it, always look for documentation.

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[-0.40862694, -0.81869507, -1.0416201 , -0.7668313 ,
           -3.3914328 , -0.37881488, -0.3009464 , -0.13645622,
           -1.4857773 , -1.4997011 , -1.1699319 , -0.32526514,
           -2.0159998 , -0.6013634 , -0.5540658 , -0.10571227,
           -4.6602955 , -0.6515625 , -0.45484787, -1.612802  ,
           -0.31550223, -0.60543936, -2.229655  , -0.39051825,
           -0.4150969 , -1.0878195 , -0.50846565, -1.5576724 ,
           -0.15930389, -0.8195685 , -0.05284442, -1.4374784 ,
           -0.20850994, -0.641809  , -0.70459646, -1.5318823 ,
           -0.1675673 , -0.13709877, -1.1764023 , -0.37570658,
           -1.4369967 , -0.2462551 , -0.03341366, -2.6779823 ,
           -0.22472051, -0.4150805 , -0.5324727 , -1.8041341 ,
           -0.30367282, -1.1377468 ]]]]], dtype=float32)>

# Tensors and Numpy

In [150]:
# numpy interacts beautifully with tensorflow
j = tf.constant(np.random.uniform(size=[50]))
j

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.73869662, 0.64186937, 0.32096507, 0.6603713 , 0.73495771,
       0.9851862 , 0.76698875, 0.82949235, 0.52624753, 0.09173601,
       0.60656511, 0.90875507, 0.46781617, 0.47911119, 0.5808816 ,
       0.19972331, 0.38003166, 0.09225594, 0.41417138, 0.04420961,
       0.15045579, 0.75903518, 0.94695228, 0.84478909, 0.34066026,
       0.15712297, 0.95552623, 0.69141032, 0.6461011 , 0.93608594,
       0.43124187, 0.98950112, 0.39427116, 0.41972412, 0.41901477,
       0.83782711, 0.69736271, 0.21274774, 0.69599882, 0.55578074,
       0.74413125, 0.8433995 , 0.82349247, 0.63004553, 0.37374701,
       0.75745945, 0.9505972 , 0.23218394, 0.75572897, 0.70248221])>

In [151]:
np.array(j) # again converted tensor into numpy array

array([0.73869662, 0.64186937, 0.32096507, 0.6603713 , 0.73495771,
       0.9851862 , 0.76698875, 0.82949235, 0.52624753, 0.09173601,
       0.60656511, 0.90875507, 0.46781617, 0.47911119, 0.5808816 ,
       0.19972331, 0.38003166, 0.09225594, 0.41417138, 0.04420961,
       0.15045579, 0.75903518, 0.94695228, 0.84478909, 0.34066026,
       0.15712297, 0.95552623, 0.69141032, 0.6461011 , 0.93608594,
       0.43124187, 0.98950112, 0.39427116, 0.41972412, 0.41901477,
       0.83782711, 0.69736271, 0.21274774, 0.69599882, 0.55578074,
       0.74413125, 0.8433995 , 0.82349247, 0.63004553, 0.37374701,
       0.75745945, 0.9505972 , 0.23218394, 0.75572897, 0.70248221])

In [152]:
tf.config.list_physical_devices('GPU') # it returns none now, because we are not having any kind of GPU for now.

[]

#ASSIGNMENT

In [153]:
scalar = tf.constant(4)
scalar, type(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 tensorflow.python.framework.ops.EagerTensor)

In [154]:
vector = tf.constant([[2,3,4,5,6]])
vector, type(vector)

(<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2, 3, 4, 5, 6]], dtype=int32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [155]:
matrix = tf.constant([[2,3,4],
                      [5,6,7]])
matrix, type(matrix)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 4],
        [5, 6, 7]], dtype=int32)>, tensorflow.python.framework.ops.EagerTensor)

In [156]:
matrix.shape, tf.size(matrix), matrix.ndim

(TensorShape([2, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=6>, 2)

In [157]:
tf.random.set_seed(42)
tensor1 = tf.constant(tf.random.uniform(shape=[1500]), shape=(5,300))
tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [158]:
tf.random.set_seed(42)
tensor2 = tf.constant(tf.random.uniform(shape=[1500]), shape=(5,300))
tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [111]:
tf.multiply(tensor1, tensor2) # using tensorflow multiplication function

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, ..., 9.8661751e-02,
        5.7661778e-01, 1.3682988e-03],
       [2.8304955e-01, 8.4855378e-02, 1.1176224e-02, ..., 2.9216504e-01,
        9.8757625e-02, 4.8427239e-02],
       [7.0630698e-03, 1.3065366e-03, 9.5515686e-01, ..., 4.6296600e-02,
        9.5767713e-01, 5.2816195e-05],
       [5.4714793e-01, 4.4264695e-01, 6.2067290e-03, ..., 5.0662118e-01,
        4.9190181e-03, 8.8531631e-01],
       [2.5158225e-02, 1.4457737e-02, 7.4083231e-02, ..., 7.7878487e-01,
        2.0520218e-02, 1.9479086e-01]], dtype=float32)>

In [160]:
tensor2 = tf.transpose(tensor2)
np.dot(tensor1, tensor2) # we had to take the transpose of the second 

array([[100.714424,  74.26969 ,  77.28432 ,  72.59379 ,  79.06383 ],
       [ 74.26969 ,  93.0812  ,  71.738365,  67.204834,  72.49768 ],
       [ 77.28432 ,  71.738365,  98.34636 ,  73.811775,  75.367256],
       [ 72.59379 ,  67.204834,  73.811775,  90.60207 ,  70.130714],
       [ 79.06383 ,  72.49768 ,  75.367256,  70.130714, 102.07891 ]],
      dtype=float32)

In [162]:
tensor3 = tf.constant(tf.random.uniform(shape=[224*224*3]), shape=(224,224,3))
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [165]:
tf.argmax(tensor3,axis=1)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[174,  58, 195],
       [ 68, 154,  75],
       [ 12,  14, 165],
       [  5,  71,  72],
       [215, 217,  30],
       [ 63,  90,  66],
       [ 12, 209,   0],
       [ 95, 132,   5],
       [ 64, 113,  10],
       [219,  38,  60],
       [135, 195, 141],
       [ 39, 139, 158],
       [ 59, 102, 115],
       [157, 223, 216],
       [177, 189,  24],
       [ 90, 167, 161],
       [141, 167,  71],
       [126, 211, 130],
       [ 83, 212, 155],
       [194, 186,  14],
       [104, 123,  77],
       [  8,  18,  83],
       [ 17, 109, 115],
       [122, 126, 132],
       [206,  69, 169],
       [ 50,  27, 124],
       [ 94,  80, 128],
       [215, 120,  87],
       [ 94, 186,  15],
       [203, 101, 131],
       [164, 214,  57],
       [130,  63, 131],
       [ 36, 165, 216],
       [ 55, 147, 223],
       [136,  10,  33],
       [  2,  27, 156],
       [ 12,  11, 124],
       [211,  50, 112],
       [ 52,  17, 102],
       [136, 187

In [166]:
tf.argmin(tensor3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[ 92, 196, 169],
       [ 45,  28,  95],
       [ 53,  61,  44],
       [197,  58, 158],
       [221,  21, 187],
       [141, 105,  79],
       [221, 182, 143],
       [ 10,  20, 223],
       [194, 116,  29],
       [126, 104,  34],
       [220, 102, 185],
       [119,  49,  28],
       [106, 222,  45],
       [206,  85, 141],
       [211,   4,  30],
       [157,  15,  67],
       [ 50, 161, 125],
       [223, 194, 103],
       [117, 194, 211],
       [133,   0, 106],
       [156, 117,  50],
       [214, 122, 223],
       [174,   6, 157],
       [134,  58,  91],
       [111,  49,  24],
       [ 30,  37, 206],
       [ 13,  45, 194],
       [193,  46, 202],
       [110,  30, 207],
       [ 89,  38, 155],
       [184,  29, 210],
       [106,  57, 148],
       [163, 153,   1],
       [ 72,  66, 187],
       [130,  83, 133],
       [ 94, 165,  73],
       [ 17, 171, 209],
       [ 19, 191,  86],
       [221,  32,   6],
       [139,  40

In [168]:
tensor4 = tf.constant(tf.random.uniform(shape=[1*224*224*3]),shape=(1,224,224,3))
tensor4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
         [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
         [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
         ...,
         [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
         [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
         [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],

        [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
         [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
         [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
         ...,
         [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
         [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
         [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],

        [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
         [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
         [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
         ...,
         [2.0133841e-01, 9.1663551e-01, 1.9890130e-01],


In [171]:
tensor4 = tf.squeeze(tensor4)

In [172]:
tensor4.shape

TensorShape([224, 224, 3])

In [189]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.normal(shape=[10]), shape=(10))
tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656],
      dtype=float32)>

In [190]:
tensor[tf.argmax(tensor)], tensor[tf.argmin(tensor)]

(<tf.Tensor: shape=(), dtype=float32, numpy=1.6994323>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.3880599>)

In [192]:
tf.argmax(tensor) # finding the position at which there is maximum element present

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [193]:
tensor = tf.cast(tensor, dtype=tf.int32) # this is the way we can change the datatype of our tensor
tf.one_hot(tensor, depth=10) # as the value are rounded, thereby most of them became zero in original tensor

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>